version: '3.1'

services:
  pg_db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=siss_db
    ports:
      - "5433:5432"

      #    volumes:
      #      - ./siss_db:/var/lib/postgresql/data
