version: '3.1'

services:
  pg_db:
    image: postgres
    restart: always
    working_dir: "/home/app/"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=siss_db
    ports:
      - "5433:5432"

      #    volumes:
      #      - ./siss_db:/var/lib/postgresql/data

  spring_tomcat:
    image: maven:3.6.3-jdk-8-slim
    working_dir: "/home/app/"
    volumes:
      - "./:/home/app/"
      - "./.m2:/root/.m2"
    command: bash -c "mvn clean spring-boot:run"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pg_db:5432/siss_db
    ports:
      - "8080:8080"
    links:
      - pg_db